### ISSUE TITLE
onSeeked event sometimes isn't triggered

### ISSUE THREAD

**Issue by Narsuf** [bitmovin/bitmovin-player-ios-sdk-cocoapod#12]
I'm using the last version of the SDK (2.11.1). And I'm having some trouble with the onSeeked event, most of the times it works fine, but there's a few times that it doesn't, and I wouldn't know to say why.

I have a function I call when a seek is finished, and I've tried using both onSeeked and onStallEnded events, but sometimes none of them works (less than 50% of the times I would say).

**Comment by hawk23** [comment]
Thank you for reporting, we are looking into it an will keep you updated on the progress,

**Comment by Narsuf** [comment]
Solved in version 2.12.0.

Thank you.
