### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by MatejBalantic** [bitmovin/bitmovin-player-ios-sdk-cocoapod#13]
Hi there

I am trying to move away from CocoaPods, so it would be great if you can offer Carthage support

**Comment by hawk23** [comment]
That's something we are already planning for the future. Will let you know as soon as that happened!

**Comment by gabors** [comment]
@hawk23 Has the future happened yet? Would love to have Carthage support as well.

**Comment by jarhoax** [comment]
@gabors @MatejBalantic Carthage support has been introduced with the latest release (`2.21.0`). 
Read more on how to get started [here](https://bitmovin.com/dashboard/player/ios).
