### ISSUE TITLE
Preroll, midroll and postroll ads not working on iOS app.

### ISSUE THREAD

**Issue by matiasCL** [bitmovin/bitmovin-player-ios-sdk-cocoapod#14]
We are trying to configure the player to trigger preroll ads, we followed the example provided here:

[https://github.com/bitmovin/bitmovin-player-ios-samples/tree/master/BasicAds](url)

After configuring the player the video starts to reproduce without triggering the preroll.

These are the workarounds we tried without success.

- Try several AdSources including the ones provided on the sample app example.
- Try to add the Bitmovin player in a CollectionViewCell instead of a ViewController (as in the example), since it's what we need for our implementation. 
- Try adding the library manually or with cocoapods.
- Inspect the request in Charles, the ad server is never called when the video is played.
- Inspect the Bitmovin webview for the player with safari developer console (the ad server is never called when the video is played

We attach a sample app where the issue is reproducible, we added 2 Bitmovin players, one inside a collectionView cell and another in a regular ViewController in order to test both cases.

[TestBitmovinAds.zip](https://github.com/bitmovin/bitmovin-player-ios-sdk-cocoapod/files/2905646/TestBitmovinAds.zip)

Thanks in advance.

**Comment by skarl-as** [comment]
I just saw this issue... not sure what you are testing but if you need AppNexus test tags let us (Spring Adtechnology) know.

E.g. here is a preroll tag that should always deliver a simple 20 sec VAST InLine clip (MediaFile node contains webm and mp4 format):
https://ib.adnxs.com/ptv?member=7823&inv_code=welt.de-desktop-werbemitteltest2_video-preroll

**Comment by michael-riha** [comment]
Thank you @matiasCL , we will look into this asap.

**Comment by michael-riha** [comment]
I can see with `Charles Proxy` that no Ad was requested in case of your app @matiasCL .
We have to investigate this deeper as it looks.

**Comment by matiasCL** [comment]
> I just saw this issue... not sure what you are testing but if you need AppNexus test tags let us (Spring Adtechnology) know.
> 
> E.g. here is a preroll tag that should always deliver a simple 20 sec VAST InLine clip (MediaFile node contains webm and mp4 format):
> https://ib.adnxs.com/ptv?member=7823&inv_code=welt.de-desktop-werbemitteltest2_video-preroll

Just tried with the test tag you sent and still not working, as @michael-riha said the Ad is not even requested so I guess the tag is not the problem.

**Comment by michael-riha** [comment]
@matiasCL the Pod for IMA was missing in your Podfile

https://github.com/bitmovin/bitmovin-player-ios-samples/blob/master/Podfile#L53

**Comment by matiasCL** [comment]
I solved the problem adding the Google IMA and Bitmovin SDK dependencies to the project, and also be sure they are added to the respective Link Binary with Libraries, Embed Frameworks in "Build Phases" as well as Embedded Binaries and Linked Frameworks and Libraries in "General" target settings.

@michael-riha there was no mention to this on the documentation provided, also it would be nice to add a section in the documentation on how to add the Bitmovin SDK manually.

**Comment by michael-riha** [comment]
@matiasCL Thank you!
