### ISSUE TITLE
Player does not mute upon calling mute after initializing player

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [bitmovin/bitmovin-player-ios-sdk-cocoapod#16]
If you call player.mute() soon after initializing the BitmovinPlayer, it won't mute.

To reproduce, modify the BasicPlayback sample app adding
```
let playbackConfig = PlaybackConfiguration()
playbackConfig.isAutoplayEnabled = true
config.playbackConfiguration = playbackConfig
```
then after `self.player = player` add `self.player?.mute()`

If however you delay that call, it does mute.
```
DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
    self.player?.mute()
}
```

As a workaround you can specify `playbackConfig.isMuted = true` however in our app sometimes we don't want it to be muted right away, but in some cases we do try to mute it very soon after initialization, but not at initialization time, so we can't really apply `playbackConfig.isMuted = true`.

**Comment by jarhoax** [comment]
Hi, 
thanks for reaching out. 

Please be aware that as soon as the `onReady` event got fired, the player is fully initialized and ready to handle API calls.
To handle your described use-case you can register to the `onReady` event and call `player?.mute()` once received.

**Comment by jordanhbuiltbyhq** [comment]
Ok I will have to work with that then, thanks!
