### ISSUE TITLE
How to get buffered percent?

### ISSUE THREAD

**Issue by buscarini** [bitmovin/bitmovin-player-ios-sdk-cocoapod#19]
I have tried the integration, and it works fine, but I haven't been able to find a way to obtain the available buffered data. I think the web player has a "forwardDuration" or something like that. Is there a way to get this information?

**Comment by stonko1994** [comment]
This feature is currently not implemented in our native SDKs. We already have an open feature request for this.

**Comment by jarhoax** [comment]
Hi @buscarini!

We added this functionality with version [`2.35.0`](https://bitmovin.com/docs/player/releases/ios/ios-2-35-0)

Please also have a look at the according [docu ](https://cdn.bitmovin.com/player/ios/2/docs/Protocols/BMPBufferApi.html).
