### ISSUE TITLE
More information about error events

### ISSUE THREAD

**Issue by buscarini** [bitmovin/bitmovin-player-ios-sdk-cocoapod#22]
The sdk has an error callback, but the documentation about this is scarce. ¿What are the possible error codes? ¿Are there fatal and non fatal errors? ¿How do I know if playback can continue?

**Comment by jarhoax** [comment]
Hi,

there are `WarningCodes` and `ErrorCodes` in the SDK. If received an error, the player gets unloaded, but can be further used by loading a new source for example. Only exception is a licensing error. There the player instance gets destroyed. 

So errors are typically stopping the possibility to continue playback and should be considered fatal. For everything else an according warning event is thrown (if applicable).

possible error codes are:
```
    BMPErrorPlayerLicenseKeyNotFound = 1016,
    BMPErrorPlayerLicenseInvalidDomain = 1017,
    BMPErrorInvalidPlayerLicenseServerUrl = 1018,
    BMPErrorJsonDeserializationFailed = 1114,
    BMPErrorPlaybackFailed = 1300,
    BMPErrorNetworkGeneral = 1400,
    BMPErrorDrmGeneral = 2000,
    BMPErrorDrmMissingConfiguration = 2001,
    BMPErrorDrmNoLicenseServerUrlProvided = 2002,
    BMPErrorDrmLicenseRequestFailed = 2003,
    BMPErrorDrmInvalidCertificate = 2011,
    BMPErrorOfflineInsufficientStorage = 2201,
    BMPErrorOfflineFailedPersistingDrmLicense = 2202,
    BMPErrorManifestDownloadFailed = 3006,
    BMPErrorBadSource = 3032
```

possible warning codes are:
```
    BMPWarningGeneral = 1000,
    BMPWarningSetupRemotePlaybackFailed = 1102,
    BMPWarningSourceCouldNotParseThumbnails = 1206,
    BMPWarningSourceHlsPlaylistTypeMissing = 1207,
    BMPWarningSourceCouldNotParseSubtitles = 1208,
    BMPWarningNetworkCouldNotLoadSubtitle = 1402,
    BMPWarningNetworkCouldNotLoadThumbnails = 1403
```

**Comment by buscarini** [comment]
Great, thanks! I somehow missed the error codes. I think it would be good if this info was displayed (or linked to) in the documentation.

**Comment by jarhoax** [comment]
> I think it would be good if this info was displayed (or linked to) in the documentation.

Yes we are working on continuously improving our docu. So there are plans to add this to the docu properly. Thanks.

**Comment by dweinber** [comment]
Thank you for your suggestions. As part of our latest major update (v3), this was added to the documentation.
In the course of this update, errors and warnings were further split into being source or player specific:

Source specific:
- https://cdn.bitmovin.com/player/ios/3/docs/Enums/BMPSourceWarningCode.html
- https://cdn.bitmovin.com/player/ios/3/docs/Enums/BMPSourceErrorCode.html

Player specific:
- https://cdn.bitmovin.com/player/ios/3/docs/Enums/BMPPlayerWarningCode.html
- https://cdn.bitmovin.com/player/ios/3/docs/Enums/BMPOfflineErrorCode.html
- https://cdn.bitmovin.com/player/ios/3/docs/Enums/BMPPlayerErrorCode.html

Please also keep in mind that this repository is deprecated, please update your project to use our up to date Cocoapods spec repository: https://github.com/bitmovin/cocoapod-specs
