### ISSUE TITLE
Player pauses at midroll ad using ima

### ISSUE THREAD

**Issue by haydenjamiesonUIC** [bitmovin/bitmovin-player-ios-sdk-cocoapod#23]
I seem to have an issue related to adbreaks following pre roll.  I have 3 adbreaks set, pre, 10% and post. It seems that once the player gets to the midroll ad, it pauses & I can see the `onPause` callback. However, the ad does not play and there is no error callback or log to aid with the diagnosis. I have validated that the correlator field is unique, and have ran the 3 ad tag requests through postman with success. 

`https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=97356`

`https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=9883`

`https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=34524`

These are the 3 tags that are used. Note that I am using the Google IMA sdk version 3.11.3, with VAST tags and Bitmovin version 2.42.0

Is there any support that can be given for this, or have I missed something in my implentation?

Thanks in advance.

**Comment by dweinber** [comment]
Hi,
Should this still be a valid issue for you, please create a support ticket via your dedicated ticketing system should you have access to one or via https://bitmovin.com/dashboard/support/tickets otherwise.

Please also keep in mind that this repository is deprecated, please update your project to use our up to date Cocoapods spec repository: https://github.com/bitmovin/cocoapod-specs
