### ISSUE TITLE
Destroy player using system UI

### ISSUE THREAD

**Issue by yoinergomez** [bitmovin/bitmovin-player-ios-sdk-cocoapod#3]
Hi,

I'm using system UI setup for BitmovinPlayer, however I can't destroy the player when get out of playback.

#### Code
You can use [this example](https://github.com/bitmovin/bitmovin-player-ios-samples/tree/master/BasicOfflinePlayback) _BasicOfflinePlayback_ for duplicate the issue but adding the following line code to setup system UI:

- In the [controller file](https://github.com/bitmovin/bitmovin-player-ios-samples/blob/master/BasicOfflinePlayback/BasicOfflinePlayback/PlaybackViewController.swift)  _PlaybackViewController.swift_ add the code to configure system UI, something like as:

```swift
let config = PlayerConfiguration()
config.sourceItem = sourceItem
// configure the player to use the systems default user interface
config.styleConfiguration.userInterfaceType = .system
```

- Run project and play any video.
- At the time of leaving by the back button, the player is not destroyed.

**Comment by hawk23** [comment]
Hi @yoinergomez! We are already aware of the issue and it will be resolved in one of the upcoming releases. We will notify you as soon as this happened.

In the meantime, you can use the default Bitmovin UI for your purposes.

**Comment by hawk23** [comment]
With iOS SDK version [2.7.0](https://github.com/bitmovin/bitmovin-player-ios-sdk-cocoapod/releases/tag/2.7.0) the issue should be resolved.

**Comment by sibe7691** [comment]
We are still seeing this issue in 2.13.1
