### ISSUE TITLE
Closed Captions is not displaying in the correct format/location

### ISSUE THREAD

**Issue by danore** [bitmovin/bitmovin-player-ios-sdk-cocoapod#31]
Hi everyone,

I need your help, I'm having problems with the subtitles (format and location) but this bug started when I did do the update to v3. I have been trying different things but I have not fixed the bug.

![bug](https://user-images.githubusercontent.com/5731639/134206943-508c3e49-0dc8-4f13-b96b-6c7cc4c21fc2.png)

**Comment by dweinber** [comment]
Hi @danore,
Please create a support ticket via your dedicated ticketing system should you have access to one or via https://bitmovin.com/dashboard/support/tickets otherwise.
