### ISSUE TITLE
Load subtitles in player

### ISSUE THREAD

**Issue by yoinergomez** [bitmovin/bitmovin-player-ios-sdk-cocoapod#4]
Hello,

I'm trying to add subtitles inside the player. However the option appears in the subtitle settings but they are not shown in the video.  

![screen shot 2018-04-18 at 10 29 57 am](https://user-images.githubusercontent.com/14276026/38943304-adc758c8-42f6-11e8-99c6-d95cf9e2c33b.png)

## Code
You can use [this sample _BasicPlayback_](https://github.com/bitmovin/bitmovin-player-ios-samples/tree/master/BasicPlayback) for duplicate the issue but adding the following lines code:

- In the [controller file](https://github.com/bitmovin/bitmovin-player-ios-samples/blob/master/BasicPlayback/BasicPlayback/ViewController.swift) _ViewController.swift_ add the setting of subtitle to player

```swift
.
.
.
// Create player based on player configuration
let player = BitmovinPlayer(configuration: config)
let subtitleURL = URL(string: "https://bitdash-a.akamaihd.net/content/sintel/subtitles/subtitles_en.vtt")
let subtitle = SubtitleTrack(url: subtitleURL, label: "English", identifier: "sub1", isDefaultTrack: true, language: "en")
player.addSubtitle(track: subtitle)
.
.
.
```

## Note:
I'm using the last version of SDK 2.7.0

**Comment by hawk23** [comment]
Hi!
At the moment we do not support side-loaded subtitles for local playback. If you add the subtitles like this, you could control them on your own by calling `cueEnter`/`cueExit` on the `SubtitleTrackController` which is returned with `subtitle.controller`. When you want to have the subtitles rendered automatically when they are set active, please reference them in the manifest file of the DASH/HLS stream.

Sidenote: The `player.addSubtitle(track:)` API call will be deprecated with version `2.8.0`.

**Comment by yoinergomez** [comment]
There is another way of load subtitles automatically without reference them in the manifest file?

**Comment by hawk23** [comment]
No, unfortunately not at the moment.

**Comment by adamszeptycki** [comment]
any reason why it's not supported?
Any tutorial / guide how to use your product to show subtitles?

**Comment by fariazz** [comment]
+1 this is a must-have

Modern web players, and the Bitmovin Android SDK, fully support passing on a Manifest + a separate subtitle file(s).

Our Manifest is automatically generate by Microsoft Media Services and only includes video and audio tracks. Our subtitles are created by rev.com, and we need to be able to pass them separately. We can't manually modify ~1500 different Manifest files.
