### ISSUE TITLE
Change color to UI player

### ISSUE THREAD

**Issue by yoinergomez** [bitmovin/bitmovin-player-ios-sdk-cocoapod#5]
Hello,

# Problem
I want to change the color to _**seekbar of the playback**_  what indicates playback progress.
![image](https://user-images.githubusercontent.com/14276026/41626535-281ca4c2-73e2-11e8-85ab-97ec75cd7f33.png)

# Code
I created a css file and add to config:
> config.styleConfiguration.playerUiCss = urlCSS

# Result
![image](https://user-images.githubusercontent.com/14276026/41626893-9bee2014-73e3-11e8-973b-fed8d63fcf26.png)

How can I do it?
Do I need override all properties?

**Comment by hawk23** [comment]
When you just want to add additional styles to the existing ones without replacing them, you need to use the `supplementalPlayerUiCss` property of the `StyleConfiguration`

    config.styleConfiguration.supplementalPlayerUiCss = urlCSS
