### ISSUE TITLE
Unable to exit full screen at the end of the video

### ISSUE THREAD

**Issue by MatejBalantic** [bitmovin/bitmovin-player-ios-sdk-cocoapod#7]
When the player is in the full-screen mode, and video reaches the end, the full-screen button becomes overlaid and it's not possible to tap it.

As a result, a user can not exit full-screen mode when the video stops.

The only way for the user to recover is to click the "replay" button which restarts the video and enables the full-screen button.

![simulator screen shot - iphone x - 2018-07-11 at 11 39 35](https://user-images.githubusercontent.com/994179/42563676-1c21985c-84ff-11e8-8d4e-7a6701f02f33.png)

cc @samek

**Comment by hawk23** [comment]
Thank you for reporting. We could reproduce the behavior and will fix it with one of the upcoming releases. I'll notify you as soon as this happened.

**Comment by samek** [comment]
Can you give us any time frame ? We’re holding the release of the app because of it. 
Thanks

**Comment by hawk23** [comment]
With today's release of iOS SDK `2.11.1` the fullscreen button is also shown in the replay overlay at the end of a stream.

**Comment by MatejBalantic** [comment]
I can confirm this works. Thanks for resolving the issue.
